name: Bug Report
description: Report a bug in agent-foundry CLI
title: "[BUG] "
labels: ["bug"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues and this is not a duplicate.
          required: true
        - label: I have tested with the latest version.
          required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `bun run list` or the version you are using.
      placeholder: "0.1.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run `bun run validate ...`
        2. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Any relevant environment details.
      placeholder: |
        - OS: macOS 15.x
        - Bun: 1.x.x
        - Shell: zsh
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Paste any relevant error output here.
      render: bash
    validations:
      required: false
